### ISSUE TITLE
Pienet alkukirjaimet defaultiksi?, make_name, clean_names

### ISSUE THREAD

**Issue by jalasalmi** [pttry/statfitools#1]
Minun mielestä on mukavampi työskennellä siten että muuttujanimet ovat kaikki pieniä kirjaimia. make_name ja clean_name -funktiot tällä hetkellä defaulttina jättää ison alkukirjaimen. Minun mielestä tämän defaultin voisi muuttaa pieneksi. Vai onko isolle alkukirjaimelle jokin hyvä syy, jota en huomaa.

**Comment by jhuovari** [comment]
Joo, käytetään pieniä. Muutin kaikki pieniksi vasta myöhemmin, joten default jäi noin että vanhat toimii. Nyt voisi muuttaa.

**Comment by jalasalmi** [comment]
Default on nyt muutettu.
